name: action-github-deployment-details
description: Github action to output deployment event details
author: PlayStudios
inputs:
    fallback_push_sha:
        description: Fallback to the commit sha when not a deployment event.
        default: false
    fallback_environment:
        description: Fallback to this environment when not a deployment event.
    fallback_application:
        description: Fallback to this application when not a deployment event.
    fallback_key_paths:
        description: Fallback to these keys when not a deployment event.
    fallback_values_file:
        description: Fallback to this values file when not a deployment event.
outputs:
    environment:
        description: The application environment to deploy into
    application:
        description: The application to deploy
    values_file:
        description: The path to the manifest values file
    key_paths:
        description: The path to the keys to update within the values file
    value:
        description: The value to set the keys to
runs:
    using: 'node12'
    main: 'lib/main.js'
