name: action-github-deployment-details
description: Github action to output deployment event details
author: PlayStudios
inputs:
    application:
        description: The application to deploy
        required: true
    values_file:
        description: Path to the values file
        required: true
    key_paths:
        description: Comma seperated list of key paths
        required: true

    push_environment:
        description: Environment used for push events
    push_value:
        description: The value used for push events, usually the git SHA
outputs:
    environment:
        description: The application environment to deploy into
    application:
        description: The application to deploy
    values_file:
        description: The path to the manifest values file
    key_paths:
        description: The path to the keys to update within the values file
    value:
        description: The value to set the keys to
runs:
    using: 'node12'
    main: 'lib/main.js'
