name: "Test typescript-action"
on:
    pull_request:
    push:
        branches:
            - master
            - 'releases/*'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1

            -   run: npm ci
            -   run: npm run build
#            -   run: npm test
            -   uses: ./
                with:
                    fallback_push_sha: "true"
                    fallback_environment: azure-trunk-east-asia
                    fallback_application: trunk-ea-lucy
                    fallback_key_paths: webapi.image.tag
                    fallback_values_file: PlayStudios/lucy/values/azure-trunk-ea.yaml
