name: "Test typescript-action"
on:
    pull_request:
    push:
        branches:
            - master
            - 'releases/*'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1

            -   run: npm ci
            -   run: npm run build
            -   run: npm test
            -   uses: ./
                with:
                    application: test-app
                    values_file: Manifests/test-app/values/trunk.yaml
                    key_paths: webapi.image.tag,cdn.image.tag
                    push_environment: trunk
                    push_value: abc123
